-- 회원정보
CREATE TABLE "MEMBER"(
	ID VARCHAR2(20) NOT NULL,
	PW VARCHAR2(2000) NOT NULL,
	AUTH CHAR(1) NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	NAME VARCHAR2(20),

	);
ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_CK" CHECK ("AUTH" IN('U','A'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY("ID");

-- 답변형 게시판
CREATE TABLE ANSWERBOARD(
	SEQ NUMBER NOT NULL,
	ID VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(4000),
	REFER NUMBER NOT NULL,
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	READCOUNT NUMBER NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
);

ALTER TABLE ANSWERBOARD ADD	CONSTRAINT "ANSWERBOARD_PK" PRIMARY KEY("SEQ");
ALTER TABLE ANSWERBOARD ADD	CONSTRAINT "ANSWERBOARD_FK" FOREIGN KEY("ID") REFERENCES "MEMBER" ("ID");